spring.application.name=ailearn
spring.ai.openai.api-key=
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

spring.ai.openai.chat.options.max-tokens=1000
spring.ai.openai.chat.options.temperature=0.3



# database credentials
spring.datasource.url=jdbc:mysql://localhost:3306/standuplearn
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#telegram credentials
telegram.bot.token=
telegram.chat.id=

